import gridDict from "../dictionary/gridDict";
import gridFunctionsEnum from "../models/gridFunctionsEnum";

export const purchaseColumns = [
  {
    field: "requesterUser",
    headerName: gridDict.requesterUser,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "purchaseOrderCount",
    headerName: gridDict.purchaseOrderCount,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderId",
    headerName: gridDict.purchaseOrderId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderTrackingCode",
    headerName: gridDict.purchaseOrderTrackingCode,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "requestCaseTrackingCode",
    headerName: gridDict.requestCaseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToProductDetails_RequestCaseId,
  },
  {
    field: "requestCaseId",
    headerName: gridDict.requestCaseId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requestCaseCreateDate",
    headerName: gridDict.requestCaseCreateDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "countOfDone",
    headerName: gridDict.countOfDone,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "commodityName",
    headerName: gridDict.commodityName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "commodityId",
    headerName: gridDict.commodityId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },

  {
    field: "purchaseTrackingCode",
    headerName: gridDict.purchaseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "requestCaseCommodityId",
    headerName: gridDict.requestCaseCommodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderDetailsId",
    headerName: gridDict.purchaseOrderDetailsId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requiredDate",
    headerName: gridDict.requiredDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "warehouseTrackingCode",
    headerName: gridDict.warehouseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToWarehouseDetails_warehouseOrderId,
  },
  {
    field: "warehouseOrderId",
    headerName: gridDict.warehouseOrderId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
];

export const warehouseGrid = [
  {
    field: "requesterUser",
    headerName: gridDict.requesterUser,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "purchaseOrderId",
    headerName: gridDict.purchaseOrderId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderTrackingCode",
    headerName: gridDict.purchaseOrderTrackingCode,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "requestCaseTrackingCode",
    headerName: gridDict.requestCaseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToProductDetails_RequestCaseId,
  },
  {
    field: "requestCaseId",
    headerName: gridDict.requestCaseId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requestCaseCreateDate",
    headerName: gridDict.requestCaseCreateDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "countOfDone",
    headerName: gridDict.countOfDone,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "commodityName",
    headerName: gridDict.commodityName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "commodityId",
    headerName: gridDict.commodityId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requestCaseCommodityId",
    headerName: gridDict.requestCaseCommodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "warehouseOrderCount",
    headerName: gridDict.warehouseOrderCount,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "requiredDate",
    headerName: gridDict.requiredDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "warehouseTrackingCode",
    headerName: gridDict.warehouseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToWarehouseDetails_warehouseOrderId,
  },
  {
    field: "warehouseOrderId",
    headerName: gridDict.warehouseOrderId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
];
