import gridDict from "../dictionary/gridDict";
import gridFunctionsEnum from "../models/gridFunctionsEnum";

export const purchaseColumns = [
  {
    field: "requesterUser",
    headerName: gridDict.requesterUser,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "purchaseOrderCount",
    headerName: gridDict.purchaseOrderCount,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderId",
    headerName: gridDict.purchaseOrderId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderTrackingCode",
    headerName: gridDict.purchaseOrderTrackingCode,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "requestCaseTrackingCode",
    headerName: gridDict.requestCaseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToProductDetails_RequestCaseId,
  },
  {
    field: "requestCaseId",
    headerName: gridDict.requestCaseId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requestCaseCreateDate",
    headerName: gridDict.requestCaseCreateDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "countOfDone",
    headerName: gridDict.countOfDone,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "commodityName",
    headerName: gridDict.commodityName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "commodityId",
    headerName: gridDict.commodityId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },

  {
    field: "purchaseTrackingCode",
    headerName: gridDict.purchaseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "requestCaseCommodityId",
    headerName: gridDict.requestCaseCommodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderDetailsId",
    headerName: gridDict.purchaseOrderDetailsId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requiredDate",
    headerName: gridDict.requiredDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "warehouseTrackingCode",
    headerName: gridDict.warehouseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToWarehouseDetails_warehouseOrderId,
  },
  {
    field: "warehouseOrderId",
    headerName: gridDict.warehouseOrderId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
];

export const warehouseGrid = [
  {
    field: "requesterUser",
    headerName: gridDict.requesterUser,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "purchaseOrderId",
    headerName: gridDict.purchaseOrderId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderTrackingCode",
    headerName: gridDict.purchaseOrderTrackingCode,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "requestCaseTrackingCode",
    headerName: gridDict.requestCaseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToProductDetails_RequestCaseId,
  },
  {
    field: "requestCaseId",
    headerName: gridDict.requestCaseId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requestCaseCreateDate",
    headerName: gridDict.requestCaseCreateDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "countOfDone",
    headerName: gridDict.countOfDone,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "commodityName",
    headerName: gridDict.commodityName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "commodityId",
    headerName: gridDict.commodityId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requestCaseCommodityId",
    headerName: gridDict.requestCaseCommodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "warehouseOrderCount",
    headerName: gridDict.warehouseOrderCount,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "requiredDate",
    headerName: gridDict.requiredDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "warehouseTrackingCode",
    headerName: gridDict.warehouseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToWarehouseDetails_warehouseOrderId,
  },
  {
    field: "warehouseOrderId",
    headerName: gridDict.warehouseOrderId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
];

export const requestCaseGrid = [
  {
    field: "requesterUser",
    headerName: gridDict.requesterUser,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "commodityName",
    headerName: gridDict.commodityName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "requiredDate",
    headerName: gridDict.requiredDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "count",
    headerName: gridDict.count,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "newcount",
    headerName: gridDict.newcount,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "trackingCode",
    headerName: gridDict.trackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToProductDetails_RequestCaseId,
  },
  {
    field: "createDate",
    headerName: gridDict.createDate,
    minWidth: 150,
    sortable: true,
    filterable: false,
    flex: 1,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "requestCaseId",
    headerName: gridDict.requestCaseId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "approvestate",
    headerName: gridDict.approvestate,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "approverName",
    headerName: gridDict.approverName,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "approveDate",
    headerName: gridDict.approveDate,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "requesterUserId",
    headerName: gridDict.requesterUserId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "isEditable",
    headerName: gridDict.isEditable,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "requestCommodityId",
    headerName: gridDict.requestCommodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "approverId",
    headerName: gridDict.approverId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "finalApprovestate",
    headerName: gridDict.finalApprovestate,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "finalApproverId",
    headerName: gridDict.finalApproverId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "finalApproverName",
    headerName: gridDict.finalApproverName,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "finalApproveDate",
    headerName: gridDict.finalApproveDate,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "scheduleActivityId",
    headerName: gridDict.scheduleActivityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "commodityId",
    headerName: gridDict.commodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderId",
    headerName: gridDict.purchaseOrderId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderTrackingCode",
    headerName: gridDict.purchaseOrderTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "exitFromWarehouseId",
    headerName: gridDict.exitFromWarehouseId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "exitFromWarehouseTrackingCode",
    headerName: gridDict.exitFromWarehouseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "exitFromWarehouseCount",
    headerName: gridDict.exitFromWarehouseCount,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseCount",
    headerName: gridDict.purchaseCount,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
];
export const requesterUserGrid = [
  {
    field: "requesterUser",
    headerName: gridDict.requesterUser,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "commodityName",
    headerName: gridDict.commodityName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "requiredDate",
    headerName: gridDict.requiredDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "purchaseOrderId",
    headerName: gridDict.purchaseOrderId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "purchaseOrderTrackingCode",
    headerName: gridDict.purchaseOrderTrackingCode,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToPurchaseDetails_purchaseOrderId,
  },
  {
    field: "requestCaseId",
    headerName: gridDict.requestCaseId,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "requestCaseTrackingCode",
    headerName: gridDict.requestCaseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToProductDetails_RequestCaseId,
  },
  {
    field: "requestCaseCreateDate",
    headerName: gridDict.requestCaseCreateDate,
    minWidth: 150,
    sortable: false,
    filterable: false,
    flex: 1,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "commodityId",
    headerName: gridDict.commodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "warehouseOrderCount",
    headerName: "تعداد سفارش از انبار",
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
  },
  {
    field: "requestCaseCommodityId",
    headerName: gridDict.requestCaseCommodityId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "countOfDone",
    headerName: gridDict.countOfDone,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "warehouseTrackingCode",
    headerName: gridDict.warehouseTrackingCode,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.navigateToWarehouseDetails_warehouseOrderId,
  },
  {
    field: "warehouseOrderId",
    headerName: gridDict.warehouseOrderId,
    minWidth: 150,
    flex: 1,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
];

export const originalItemsGrid = [
  {
    field: "id",
    headerName: gridDict.id,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "name",
    headerName: gridDict.name,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "subItems",
    headerName: gridDict.subItems,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "actions",
    headerName: gridDict.actions,
    description: "ActionColumn",
    sortable: false,
    minWidth: 150,
    flex: 1,
    filterable: false,
    hideSortIcons: true,
    type: "actions",
    cellClassName: "actions",
    disableColumnMenu: true,
    renderType: gridFunctionsEnum.actionEditColumn,
  },
];

export const subItemsGrid = [
  {
    field: "id",
    headerName: gridDict.id,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "name",
    headerName: gridDict.name,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "allCheckList",
    headerName: gridDict.allCheckList,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "allFloor",
    headerName: gridDict.allFloor,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "allProjects",
    headerName: gridDict.allProjects,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "allUnit",
    headerName: gridDict.allUnit,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "originalItemName",
    headerName: gridDict.originalItemName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "relatedCheckList",
    headerName: gridDict.relatedCheckList,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "relatedFloor",
    headerName: gridDict.relatedFloor,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "relatedProjects",
    headerName: gridDict.relatedProjects,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "relatedUnit",
    headerName: gridDict.relatedUnit,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "actions",
    headerName: gridDict.actions,
    description: "ActionColumn",
    sortable: false,
    minWidth: 150,
    flex: 1,
    filterable: false,
    hideSortIcons: true,
    type: "actions",
    cellClassName: "actions",
    disableColumnMenu: true,
    renderType: gridFunctionsEnum.actionEditColumn,
  },
];

export const usabilitiesGrid = [
  {
    field: "id",
    headerName: gridDict.id,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "usablityName",
    headerName: gridDict.usablityName,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
  },
  {
    field: "units",
    headerName: gridDict.units,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.actionCustom,
  },
  {
    field: "code",
    headerName: gridDict.code,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showNumberColumns,
  },
  {
    field: "createDate",
    headerName: gridDict.createDate,
    flex: 1,
    minWidth: 150,
    editable: false,
    filterable: false,
    renderType: gridFunctionsEnum.showDateColumns,
  },
  {
    field: "actions",
    headerName: gridDict.actions,
    description: "ActionColumn",
    sortable: false,
    minWidth: 150,
    flex: 1,
    filterable: false,
    hideSortIcons: true,
    type: "actions",
    cellClassName: "actions",
    disableColumnMenu: true,
    renderType: gridFunctionsEnum.actionEditColumn,
  },
];
